name: Build and Deploy Streamlit Container to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6DB0444203034E6CBF2F9D5E622957DA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4CE948718F3740F8B70442E8D8A55AE5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5AB0FC391E7A4281B48D416599B7EDFD }}

      - name: Build and push container image to ACR
        uses: azure/acr-build@v1
        with:
          registry: coolpizzawinter.azurecr.io
          image: streamlit-app:latest
          dockerfile: dockerfile1
          context: .

      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-deploy@v3
        with:
          app-name: streamlit-pr
          images: coolpizzawinter.azurecr.io/streamlit-app:latest
